### ISSUE TITLE
franken: Missing delegation for 10.50.60.0/22 ASN 4242420205

### ISSUE THREAD

**Issue by ecsv** [freifunk/icvpn-meta#525]
@RedDog99, @mayosemmel

I am currently seeing ROA check errors in my bird logs on vogtland1:

    ROA check failed for 10.50.60.0/22 ASN 4242420205

It seems like either some delegation is missing (see #522) or some dn42 user announces a conflicting range. Please investigate

**Comment by RedDog99** [comment]
Hi Sven

Am Sonntag, den 17.09.2017, 08:47 +0000 schrieb Sven Eckelmann:
> @RedDog99, @mayosemmel
> I am currently seeing ROA check errors in my bird logs on vogtland1:
> ROA check failed for 10.50.60.0/22 ASN 4242420205
> It seems like either some delegation is missing (see #522) or some
> dn42 user announces a conflicting range. Please investigate

We didn't delegate this range. Looks like a conflict.

Chrisnew (our dn42 contact) contacted the probably origin of this
announcement.

It looks like an general failure, that non-dn42 subnets are announced
via dn42 links. I would highly recommend, that every icvpn - dn42
bridge configures filters, so that only the dn42 network (172.20/14)
could be announced into the icvpn.

Tim

**Comment by mweinelt** [comment]
That is not enforcible, which is why ROA will work just fine against these collisions.

**Comment by RedDog99** [comment]
Hi

Why you can't set a prefix-list?

Tim

Am 18. September 2017 00:15:44 MESZ schrieb hexa- <notifications@github.com>:
>That is not enforcible, which is why ROA will work just fine against
>these collisions.

**Comment by mweinelt** [comment]
Because there a valid peers forwarding freifunk traffic on dn42.

**Comment by chrisnew** [comment]
I’m forwarding valid freifunk traffic on dn42 as well. Either we start to implement ROA on non-dn42 as well or we hope people will be more careful when announcing prefixes.

**Comment by chrisnew** [comment]
fyi, it should be solved now
